# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            githubContentClient:
                base_uri: https://raw.githubusercontent.com
                headers:
<<<<<<< HEAD
                    Authorization: 'Token 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'
=======
                    Authorization: 'Token YOUR_TOKEN'
>>>>>>> eb94ae3ab4d01c108d42181cb9a702fb46b44531



when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
    
